# Конфигурация настроена под FOV 90 у клиента (Видимость: 90 в настройках МК).

menu:
  world: world
  x: 0.5
  y: 150.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

menus:
  main:
    buttons:
      - play
      - shop
      - locker
      - settings
      - social
  settings:
    buttons:
      - fov_dec
      - fov_inc
      - continue
